### PR TITLE
provider certManager.server override option

### LINKED ISSUE #24: Allow ACME override (so we can use LetsEncrypt staging for testing things)
* Create a `letsencrypt-staging` ClusterIssuer, in addition to the regular prod one.
* Create a `useLetsEncryptStaging` boolean flag.
* When `useLetsEncryptStaging` is `true`, MDE's Ingresses should be annotated to request certs from LetsEncrypt staging instead of production.

### PR DESCRIPTION
**Pull request by jwietelmann**
fixes #24

### CODE REVIEW

**Review by grossvogel — APPROVED** [review]

**Review by vaxinate — APPROVED** [review]
I only have the nitpick of wondering if `server` is too ambiguous where it should be like `acmeServer` or something /shrug

**Comment by jwietelmann** [comment]
@vaxinate Thinking about that actually gave me perhaps a better idea:

Instead of having a server override, what if I just create another issuer for `letsencrypt-staging` and have a config flag `useLetsEncryptStaging` to tell MDE to use the staging issuer for MDE ingresses?

**Comment by vaxinate** [comment]
i like that idea

**Comment by iamjoshfrank** [comment]
Is that set in the values file, so that you're telling MDE what to use before running the install script?

**Comment by grossvogel** [comment]
@iamjoshfrank yeah but in the new proposed way you could theoretically you could go back and install or change things to use _real_ letsencrypt w/o having to make any changes to the cert-manager config. The original approach would have made the whole cluster bound to the staging setup.

**Comment by iamjoshfrank** [comment]
Cool. Makes sense to me.

**Comment by jwietelmann** [comment]
Cool, I'm going to close this, go change the issue, and proceed with the new plan.

**Pull request closed without merging**
