### PR TITLE
certmanager dns-01 with route53

### PR DESCRIPTION
**Pull request by oohnoitz**
This adds some logic for enabling support for DNS01 with Route53.

### CODE REVIEW

**Comment by bit-herder** [comment]
do we need to bump the cert manager annotations?

**Comment by oohnoitz** [comment]
which annotations? or do you mean the docs?

**Comment by bit-herder** [comment]
sorry i just woke up. the api-versions of the cluster issuers that tripped us up. maybe they are right idk from memory

**Comment by oohnoitz** [comment]
all good, the versions match up here. we aren't bumping up the cert-manager chart at all so this should still be valid since i copied from the ones in this repo before modifying them.

**Comment by bit-herder** [comment]
that’s another challenge going forward heh bumping versions . cool thanks for looking

**Review by bit-herder — APPROVED** [review]
lg2m

**Pull request merged**
