### PR TITLE
put all pki config under one section

### PR DESCRIPTION
**Pull request by jwietelmann**
Connects to #20

### CODE REVIEW

**Comment by grossvogel** [comment]
Just finished testing using the new format with PKI from our-terraform in `config/values.yaml`. Uninstalling and checking with files in `config/pki`

**Comment by grossvogel** [comment]
Finished checking with files in `config/pki` instead of values, and it appears to be working fine. I just made a couple of small changes to the name of the healthcheck client configs and docs.

**Review by grossvogel — APPROVED** [review]
@jwietelmann these are the adjustments I made:
https://github.com/revelrylabs/moondog-engine/pull/42/commits/00836cf2f9a49887fa873880fc299295a906afe2

**Review by bit-herder — APPROVED** [review]
if jason tested it thats good enough for me.

**Pull request merged**
